"FINAL TESTING OF THIS PROJECT IS PENDING"
"I RAN OUT OF MY MONTHLY QUOTA TO USE THE SHEETY API"
"HOW EVER THE CODE WILL WORK THE WAY IT NEEDS TO AS LONG AS YOU PUT IN YOUR API KEYS"
"I WILL COME BACK AN UPDATE THIS REPOSITORY AS SOON AS I CAN TEST AGAIN"